project:
  type: website

website:
  title: "Baseball"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Home runs"
        href: home-runs.qmd

execute:
  echo: false

format:
  html:
    theme: cosmo
